### ISSUE TITLE
reuse the original url after login

### ISSUE THREAD

**Issue by zanpak** [vikinganalytics/daeploy-issues#68]

**Comment by OskarLiew** [comment]
I think this one and #70 are solved by the same thing, namely [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS). The [Headers](https://doc.traefik.io/traefik/v2.0/middlewares/headers/) middleware should probably be included with the existing forwardAuth middleware using [Chain](https://doc.traefik.io/traefik/v2.0/middlewares/chain/) to send an origin header when redirected to the login and verify endpoints.
